name: theme
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  shared:
    path: ../shared

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
