name: flutter_flavors
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

workspace:
  - packages/environment
  - packages/shared

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  environment:
    path: ./packages/environment
  shared:
    path: ./packages/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
