name: assets
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/animations/
flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
  output: lib/src/generated/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true