name: environment
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1


resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
